package net.survival.interaction;

public enum MessagePriority
{
    RESERVED_PRE_STEP,
    RESERVED_STEP,
    GAMEPLAY_PRE_STEP,
    GAMEPLAY_STEP,
    GAMEPLAY_POST_STEP,
    GAMEPLAY_DRAW,
    RESERVED_POST_STEP,
    RESERVED_PRE_DRAW,
    RESERVED_DRAW,
    RESERVED_DRAW_DRAW
}