/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_MappedSubresource */

#ifndef _Included_dev_josh127_libwin32_D3D11_MappedSubresource
#define _Included_dev_josh127_libwin32_D3D11_MappedSubresource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_MappedSubresource
 * Method:    create
 * Signature: (Ljava/nio/ByteBuffer;II)Ldev/josh127/libwin32/D3D11/MappedSubresource;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024MappedSubresource_create
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     dev_josh127_libwin32_D3D11_MappedSubresource
 * Method:    getData
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024MappedSubresource_getData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
