/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_Device */

#ifndef _Included_dev_josh127_libwin32_D3D11_Device
#define _Included_dev_josh127_libwin32_D3D11_Device
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_Device
 * Method:    createBlendState
 * Signature: (Ldev/josh127/libwin32/D3D11/BlendDesc;)Ldev/josh127/libwin32/D3D11/BlendState;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Device_createBlendState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_Device
 * Method:    createBuffer
 * Signature: (Ldev/josh127/libwin32/D3D11/BufferDesc;Ldev/josh127/libwin32/D3D11/SubresourceData;)Ldev/josh127/libwin32/D3D11/Buffer;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Device_createBuffer
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_Device
 * Method:    createDepthStencilState
 * Signature: (Ldev/josh127/libwin32/D3D11/DepthStencilDesc;)Ldev/josh127/libwin32/D3D11/DepthStencilState;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Device_createDepthStencilState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_Device
 * Method:    createDepthStencilView
 * Signature: (Ldev/josh127/libwin32/D3D11/Resource;Ldev/josh127/libwin32/D3D11/DepthStencilViewDesc;)Ldev/josh127/libwin32/D3D11/DepthStencilView;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Device_createDepthStencilView
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_Device
 * Method:    createInputLayout
 * Signature: ([Ldev/josh127/libwin32/D3D11/InputElementDesc;Ljava/nio/ByteBuffer;)Ldev/josh127/libwin32/D3D11/InputLayout;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Device_createInputLayout
  (JNIEnv *, jobject, jobjectArray, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_Device
 * Method:    createPixelShader
 * Signature: (Ljava/nio/ByteBuffer;Ldev/josh127/libwin32/D3D11/ClassLinkage;)Ldev/josh127/libwin32/D3D11/PixelShader;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Device_createPixelShader
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_Device
 * Method:    createRasterizerState
 * Signature: (Ldev/josh127/libwin32/D3D11/RasterizerDesc;)Ldev/josh127/libwin32/D3D11/RasterizerState;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Device_createRasterizerState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_Device
 * Method:    createRenderTargetView
 * Signature: (Ldev/josh127/libwin32/D3D11/Resource;Ldev/josh127/libwin32/D3D11/RenderTargetViewDesc;)Ldev/josh127/libwin32/D3D11/RenderTargetView;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Device_createRenderTargetView
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_Device
 * Method:    createSamplerState
 * Signature: (Ldev/josh127/libwin32/D3D11/SamplerDesc;)Ldev/josh127/libwin32/D3D11/SamplerState;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Device_createSamplerState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_Device
 * Method:    createShaderResourceView
 * Signature: (Ldev/josh127/libwin32/D3D11/Resource;Ldev/josh127/libwin32/D3D11/ShaderResourceViewDesc;)Ldev/josh127/libwin32/D3D11/ShaderResourceView;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Device_createShaderResourceView
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_Device
 * Method:    createTexture2D
 * Signature: (Ldev/josh127/libwin32/D3D11/Texture2DDesc;Ldev/josh127/libwin32/D3D11/SubresourceData;)Ldev/josh127/libwin32/D3D11/Texture2D;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Device_createTexture2D
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_Device
 * Method:    createVertexShader
 * Signature: (Ljava/nio/ByteBuffer;Ldev/josh127/libwin32/D3D11/ClassLinkage;)Ldev/josh127/libwin32/D3D11/VertexShader;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Device_createVertexShader
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_Device
 * Method:    getImmediateContext
 * Signature: ()Ldev/josh127/libwin32/D3D11/DeviceContext;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Device_getImmediateContext
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
