/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_LibWin32Startup */

#ifndef _Included_dev_josh127_libwin32_LibWin32Startup
#define _Included_dev_josh127_libwin32_LibWin32Startup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_LibWin32Startup
 * Method:    nativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_josh127_libwin32_LibWin32Startup_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
