/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_Dxgi_SwapChain */

#ifndef _Included_dev_josh127_libwin32_Dxgi_SwapChain
#define _Included_dev_josh127_libwin32_Dxgi_SwapChain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_Dxgi_SwapChain
 * Method:    getBuffer
 * Signature: (I)Ldev/josh127/libwin32/D3D11/Texture2D;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_Dxgi_00024SwapChain_getBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     dev_josh127_libwin32_Dxgi_SwapChain
 * Method:    present
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_Dxgi_00024SwapChain_present
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
