/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_DeviceContext */

#ifndef _Included_dev_josh127_libwin32_D3D11_DeviceContext
#define _Included_dev_josh127_libwin32_D3D11_DeviceContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    clearDepthStencilView
 * Signature: (Ldev/josh127/libwin32/D3D11/DepthStencilView;IFB)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_clearDepthStencilView
  (JNIEnv *, jobject, jobject, jint, jfloat, jbyte);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    clearRenderTargetView
 * Signature: (Ldev/josh127/libwin32/D3D11/RenderTargetView;FFFF)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_clearRenderTargetView
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    draw
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_draw
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    drawIndexed
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_drawIndexed
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    generateMips
 * Signature: (Ldev/josh127/libwin32/D3D11/ShaderResourceView;)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_generateMips
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    iaSetIndexBuffer
 * Signature: (Ldev/josh127/libwin32/D3D11/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_iaSetIndexBuffer
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    iaSetInputLayout
 * Signature: (Ldev/josh127/libwin32/D3D11/InputLayout;)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_iaSetInputLayout
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    iaSetPrimitiveTopology
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_iaSetPrimitiveTopology
  (JNIEnv *, jobject, jint);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    iaSetVertexBuffers
 * Signature: (I[Ldev/josh127/libwin32/D3D11/Buffer;[I[I)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_iaSetVertexBuffers
  (JNIEnv *, jobject, jint, jobjectArray, jintArray, jintArray);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    omSetBlendState
 * Signature: (Ldev/josh127/libwin32/D3D11/BlendState;[FI)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_omSetBlendState
  (JNIEnv *, jobject, jobject, jfloatArray, jint);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    omSetDepthStencilState
 * Signature: (Ldev/josh127/libwin32/D3D11/DepthStencilState;I)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_omSetDepthStencilState
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    omSetRenderTargets
 * Signature: ([Ldev/josh127/libwin32/D3D11/RenderTargetView;Ldev/josh127/libwin32/D3D11/DepthStencilView;)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_omSetRenderTargets
  (JNIEnv *, jobject, jobjectArray, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    psSetConstantBuffers
 * Signature: (I[Ldev/josh127/libwin32/D3D11/Buffer;)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_psSetConstantBuffers
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    psSetSamplers
 * Signature: (I[Ldev/josh127/libwin32/D3D11/SamplerState;)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_psSetSamplers
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    psSetShader
 * Signature: (Ldev/josh127/libwin32/D3D11/PixelShader;[Ldev/josh127/libwin32/D3D11/ClassInstance;)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_psSetShader
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    psSetShaderResources
 * Signature: (I[Ldev/josh127/libwin32/D3D11/ShaderResourceView;)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_psSetShaderResources
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    rsSetScissorRects
 * Signature: ([Ldev/josh127/libwin32/Rect;)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_rsSetScissorRects
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    rsSetState
 * Signature: (Ldev/josh127/libwin32/D3D11/RasterizerState;)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_rsSetState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    rsSetViewports
 * Signature: ([Ldev/josh127/libwin32/D3D11/Viewport;)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_rsSetViewports
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    updateSubresource
 * Signature: (Ldev/josh127/libwin32/D3D11/Resource;ILdev/josh127/libwin32/D3D11/Box;Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_updateSubresource
  (JNIEnv *, jobject, jobject, jint, jobject, jobject, jint, jint);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    map
 * Signature: (Ldev/josh127/libwin32/D3D11/Resource;III)Ldev/josh127/libwin32/D3D11/MappedSubresource;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_map
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    unmap
 * Signature: (Ldev/josh127/libwin32/D3D11/Resource;I)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_unmap
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    vsSetConstantBuffers
 * Signature: (I[Ldev/josh127/libwin32/D3D11/Buffer;)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_vsSetConstantBuffers
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    vsSetSamplers
 * Signature: (I[Ldev/josh127/libwin32/D3D11/SamplerState;)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_vsSetSamplers
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    vsSetShader
 * Signature: (Ldev/josh127/libwin32/D3D11/VertexShader;[Ldev/josh127/libwin32/D3D11/ClassInstance;)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_vsSetShader
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceContext
 * Method:    vsSetShaderResources
 * Signature: (I[Ldev/josh127/libwin32/D3D11/ShaderResourceView;)V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceContext_vsSetShaderResources
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
