/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_DepthStencilDesc */

#ifndef _Included_dev_josh127_libwin32_D3D11_DepthStencilDesc
#define _Included_dev_josh127_libwin32_D3D11_DepthStencilDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_DepthStencilDesc
 * Method:    create
 * Signature: (ZIIZBBLdev/josh127/libwin32/D3D11/DepthStencilOpDesc;Ldev/josh127/libwin32/D3D11/DepthStencilOpDesc;)Ldev/josh127/libwin32/D3D11/DepthStencilDesc;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024DepthStencilDesc_create
  (JNIEnv *, jclass, jboolean, jint, jint, jboolean, jbyte, jbyte, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
