/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_BlendDesc */

#ifndef _Included_dev_josh127_libwin32_D3D11_BlendDesc
#define _Included_dev_josh127_libwin32_D3D11_BlendDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_BlendDesc
 * Method:    create
 * Signature: (ZZ[Ldev/josh127/libwin32/D3D11/RenderTargetBlendDesc;)Ldev/josh127/libwin32/D3D11/BlendDesc;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024BlendDesc_create
  (JNIEnv *, jclass, jboolean, jboolean, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
