/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_Rect */

#ifndef _Included_dev_josh127_libwin32_Rect
#define _Included_dev_josh127_libwin32_Rect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_Rect
 * Method:    create
 * Signature: (IIII)Ldev/josh127/libwin32/Rect;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_Rect_create
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
