/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_InputElementDesc */

#ifndef _Included_dev_josh127_libwin32_D3D11_InputElementDesc
#define _Included_dev_josh127_libwin32_D3D11_InputElementDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_InputElementDesc
 * Method:    create
 * Signature: (Ljava/lang/String;IIIIII)Ldev/josh127/libwin32/D3D11/InputElementDesc;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024InputElementDesc_create
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
