/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_Viewport */

#ifndef _Included_dev_josh127_libwin32_D3D11_Viewport
#define _Included_dev_josh127_libwin32_D3D11_Viewport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_Viewport
 * Method:    create
 * Signature: (FFFFFF)Ldev/josh127/libwin32/D3D11/Viewport;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Viewport_create
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
