/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_SubresourceData */

#ifndef _Included_dev_josh127_libwin32_D3D11_SubresourceData
#define _Included_dev_josh127_libwin32_D3D11_SubresourceData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_SubresourceData
 * Method:    create
 * Signature: (Ljava/nio/ByteBuffer;II)Ldev/josh127/libwin32/D3D11/SubresourceData;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024SubresourceData_create
  (JNIEnv *, jclass, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
