/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_Dxgi_SwapChainDesc */

#ifndef _Included_dev_josh127_libwin32_Dxgi_SwapChainDesc
#define _Included_dev_josh127_libwin32_Dxgi_SwapChainDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_Dxgi_SwapChainDesc
 * Method:    create
 * Signature: (Ldev/josh127/libwin32/Dxgi/ModeDesc;Ldev/josh127/libwin32/Dxgi/SampleDesc;IILdev/josh127/libwin32/NativePtr;ZII)Ldev/josh127/libwin32/Dxgi/SwapChainDesc;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_Dxgi_00024SwapChainDesc_create
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jobject, jboolean, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
