/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_PodStruct */

#ifndef _Included_dev_josh127_libwin32_PodStruct
#define _Included_dev_josh127_libwin32_PodStruct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_PodStruct
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_PodStruct_free
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
