/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_Texture2DDesc */

#ifndef _Included_dev_josh127_libwin32_D3D11_Texture2DDesc
#define _Included_dev_josh127_libwin32_D3D11_Texture2DDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_Texture2DDesc
 * Method:    create
 * Signature: (IIIIILdev/josh127/libwin32/Dxgi/SampleDesc;IIII)Ldev/josh127/libwin32/D3D11/Texture2DDesc;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Texture2DDesc_create
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
