/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_Box */

#ifndef _Included_dev_josh127_libwin32_D3D11_Box
#define _Included_dev_josh127_libwin32_D3D11_Box
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_Box
 * Method:    create
 * Signature: (IIIIII)Ldev/josh127/libwin32/D3D11/Box;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Box_create
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
