/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_Dxgi_ModeDesc */

#ifndef _Included_dev_josh127_libwin32_Dxgi_ModeDesc
#define _Included_dev_josh127_libwin32_Dxgi_ModeDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_Dxgi_ModeDesc
 * Method:    create
 * Signature: (IILdev/josh127/libwin32/Dxgi/Rational;III)Ldev/josh127/libwin32/Dxgi/ModeDesc;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_Dxgi_00024ModeDesc_create
  (JNIEnv *, jclass, jint, jint, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
