/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_DepthStencilOpDesc */

#ifndef _Included_dev_josh127_libwin32_D3D11_DepthStencilOpDesc
#define _Included_dev_josh127_libwin32_D3D11_DepthStencilOpDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_DepthStencilOpDesc
 * Method:    create
 * Signature: (IIII)Ldev/josh127/libwin32/D3D11/DepthStencilOpDesc;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024DepthStencilOpDesc_create
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
