/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_Dxgi_SampleDesc */

#ifndef _Included_dev_josh127_libwin32_Dxgi_SampleDesc
#define _Included_dev_josh127_libwin32_Dxgi_SampleDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_Dxgi_SampleDesc
 * Method:    create
 * Signature: (II)Ldev/josh127/libwin32/Dxgi/SampleDesc;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_Dxgi_00024SampleDesc_create
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
