/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_DeviceDeviceContextSwapChainTuple */

#ifndef _Included_dev_josh127_libwin32_D3D11_DeviceDeviceContextSwapChainTuple
#define _Included_dev_josh127_libwin32_D3D11_DeviceDeviceContextSwapChainTuple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceDeviceContextSwapChainTuple
 * Method:    getDevice
 * Signature: ()Ldev/josh127/libwin32/D3D11/Device;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceDeviceContextSwapChainTuple_getDevice
  (JNIEnv *, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceDeviceContextSwapChainTuple
 * Method:    getDeviceContext
 * Signature: ()Ldev/josh127/libwin32/D3D11/DeviceContext;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceDeviceContextSwapChainTuple_getDeviceContext
  (JNIEnv *, jobject);

/*
 * Class:     dev_josh127_libwin32_D3D11_DeviceDeviceContextSwapChainTuple
 * Method:    getSwapChain
 * Signature: ()Ldev/josh127/libwin32/Dxgi/SwapChain;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024DeviceDeviceContextSwapChainTuple_getSwapChain
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
