/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_SamplerDesc */

#ifndef _Included_dev_josh127_libwin32_D3D11_SamplerDesc
#define _Included_dev_josh127_libwin32_D3D11_SamplerDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_SamplerDesc
 * Method:    create
 * Signature: (IIIIFII[FFF)Ldev/josh127/libwin32/D3D11/SamplerDesc;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024SamplerDesc_create
  (JNIEnv *, jclass, jint, jint, jint, jint, jfloat, jint, jint, jfloatArray, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
