/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_Dxgi_Rational */

#ifndef _Included_dev_josh127_libwin32_Dxgi_Rational
#define _Included_dev_josh127_libwin32_Dxgi_Rational
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_Dxgi_Rational
 * Method:    create
 * Signature: (II)Ldev/josh127/libwin32/Dxgi/Rational;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_Dxgi_00024Rational_create
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
