/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_ComObject */

#ifndef _Included_dev_josh127_libwin32_ComObject
#define _Included_dev_josh127_libwin32_ComObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_ComObject
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_josh127_libwin32_ComObject_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
