/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_BufferDesc */

#ifndef _Included_dev_josh127_libwin32_D3D11_BufferDesc
#define _Included_dev_josh127_libwin32_D3D11_BufferDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_BufferDesc
 * Method:    create
 * Signature: (IIIIII)Ldev/josh127/libwin32/D3D11/BufferDesc;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024BufferDesc_create
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
