/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_RenderTargetBlendDesc */

#ifndef _Included_dev_josh127_libwin32_D3D11_RenderTargetBlendDesc
#define _Included_dev_josh127_libwin32_D3D11_RenderTargetBlendDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_RenderTargetBlendDesc
 * Method:    create
 * Signature: (ZIIIIIIB)Ldev/josh127/libwin32/D3D11/RenderTargetBlendDesc;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024RenderTargetBlendDesc_create
  (JNIEnv *, jclass, jboolean, jint, jint, jint, jint, jint, jint, jbyte);

#ifdef __cplusplus
}
#endif
#endif
