/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_RasterizerDesc */

#ifndef _Included_dev_josh127_libwin32_D3D11_RasterizerDesc
#define _Included_dev_josh127_libwin32_D3D11_RasterizerDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_RasterizerDesc
 * Method:    create
 * Signature: (IIZIFFZZZZ)Ldev/josh127/libwin32/D3D11/RasterizerDesc;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024RasterizerDesc_create
  (JNIEnv *, jclass, jint, jint, jboolean, jint, jfloat, jfloat, jboolean, jboolean, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
