/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_josh127_libwin32_D3D11_Texture2D */

#ifndef _Included_dev_josh127_libwin32_D3D11_Texture2D
#define _Included_dev_josh127_libwin32_D3D11_Texture2D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_josh127_libwin32_D3D11_Texture2D
 * Method:    getDesc
 * Signature: ()Ldev/josh127/libwin32/D3D11/Texture2DDesc;
 */
JNIEXPORT jobject JNICALL Java_dev_josh127_libwin32_D3D11_00024Texture2D_getDesc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
